# written by NyCode (https://github.com/NyCodeGHG/bcrypt/blob/main/.github/workflows/ci.yml)
name: Gradle CI
on: [ push, pull_request ]

jobs:

  gradleValidation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4.1.5

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3.3.2

  build:
    runs-on: ubuntu-latest
    needs: gradleValidation
    name: Build
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4.1.5

      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: 11

      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build with Gradle
        run: ./gradlew assemble
  test:
    runs-on: ubuntu-latest
    name: Test
    needs: build
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4.1.5

      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: 11

      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run Tests
        run: ./gradlew check
  publish-docs:
    runs-on: ubuntu-latest
    name: Publish Docs
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && !contains(github.event.commits[0].message, '[skip ci]')
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4.1.5

      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: 11

      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build Dokka Docs with Gradle
        run: ./gradlew dokkaHtml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/dokka/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
